function prepared = prepareGARSOSSTMData( ...
    metaManifest, reconstructionDir, referenceVolumeA, forceUpdate, varargin)
%prepareGARSOSSTMDATA Prepare shared GAR-SOS inputs for STM reconstruction.
%
% The raw/preprocessed data are loaded once through loadPrepareGARSOSData.
% Calibration metadata are generated by prepareGARSOSCalibrationData and
% retained in prepared.calibrationManifest.

    if nargin < 4 || isempty(forceUpdate)
        forceUpdate = false;
    end
    p = inputParser;
    addParameter(p, 'SequenceIndex', 1, ...
        @(x) isnumeric(x) && isscalar(x) && x >= 1 && x == floor(x));
    addParameter(p, 'FrameParams', [], @(x) isempty(x) || isstruct(x));
    addParameter(p, 'GriddingParams', struct(), @isstruct);
    addParameter(p, 'PreparedData', [], @(x) isempty(x) || isstruct(x));
    parse(p, varargin{:});

    iSequence = p.Results.SequenceIndex;
    if ~isstruct(metaManifest) || ~isfield(metaManifest, 'sequences') || ...
            numel(metaManifest.sequences) ~= 1 || iSequence ~= 1
        error('prepareGARSOSSTMData:SingleSequenceRequired', ...
            'GAR-SOS STM preparation supports exactly one sequence.');
    end
    if isempty(p.Results.FrameParams)
        frameParams = struct( ...
            'nSpokesPerFrame', 15, ...
            'zSlice', [], ...
            'calibrationSize', [32 32]);
    else
        frameParams = p.Results.FrameParams;
    end
    griddingParams = p.Results.GriddingParams;
    if isempty(p.Results.PreparedData)
        prepared = loadPrepareGARSOSData( ...
            metaManifest, referenceVolumeA, griddingParams, ...
            'SequenceIndex', iSequence);
    else
        prepared = p.Results.PreparedData;
    end

    frameParams = localResolveFrameParams( ...
        frameParams, prepared.dimensions.imageSize(3));
    if ~isfield(griddingParams, 'imageSize') || isempty(griddingParams.imageSize)
        griddingParams.imageSize = prepared.dimensions.imageSize;
    end
    if ~isfield(griddingParams, 'gridOversamplingFactor') || ...
            isempty(griddingParams.gridOversamplingFactor)
        griddingParams.gridOversamplingFactor = 1.375;
    end

    [calibrationManifest, calibrationManifestFile, stmCalibOutputs] = ...
        prepareGARSOSCalibrationData( ...
        metaManifest, reconstructionDir, referenceVolumeA, ...
        frameParams, griddingParams, forceUpdate, ...
        'PreparedData', prepared);

    prepared.manifest = calibrationManifest;
    prepared.manifestFile = calibrationManifestFile;
    prepared.calibrationManifest = calibrationManifest;
    prepared.calibrationManifestFile = calibrationManifestFile;
    prepared.calibData = calibrationManifest.sequences(iSequence).calibData;
    prepared.stmCalibOutputs = stmCalibOutputs;
    prepared.frameParams = frameParams;
    prepared.griddingParams = griddingParams;
end

function frameParams = localResolveFrameParams(frameParams, nZ)
    required = {'nSpokesPerFrame', 'zSlice', 'calibrationSize'};
    if ~isstruct(frameParams) || ~all(isfield(frameParams, required))
        error('prepareGARSOSSTMData:InvalidFrameParams', ...
            'FrameParams must contain nSpokesPerFrame, zSlice, calibrationSize.');
    end
    validateattributes(frameParams.nSpokesPerFrame, {'numeric'}, ...
        {'scalar', 'integer', 'positive'});
    validateattributes(frameParams.calibrationSize, {'numeric'}, ...
        {'vector', 'numel', 2, 'integer', 'positive'});
    if isempty(frameParams.zSlice)
        frameParams.zSlice = 1:nZ;
    else
        validateattributes(frameParams.zSlice, {'numeric'}, ...
            {'vector', 'integer', 'positive'});
        if any(frameParams.zSlice > nZ)
            error('prepareGARSOSSTMData:InvalidZSlice', ...
                'FrameParams.zSlice exceeds the image-space z dimension.');
        end
        frameParams.zSlice = unique(frameParams.zSlice(:).', 'stable');
    end
end
