function [kCal, outputs, diagnostics] = reconstructGARFrameForSTMCoordinateAware(prepared, nSpokesPerFrame, zSlice, calibrationSize, varargin)
%reconstructGARFRAMEFORSTMCOORDINATEAWARE Apply prepared geometry to STM prep.

    required = {'sampledData','kSpaceLocations','DCF','spokeIndex','sensitivityMaps','dimensions','CA','Cb'};
    if ~isstruct(prepared) || ~all(isfield(prepared, required))
        error('reconstructGARFrameForSTMCoordinateAware:InvalidPreparedData', ...
            'prepared is missing one or more shared-preparation fields.');
    end
    d = prepared.dimensions;
    [kCal, outputs, diagnostics] = reconstructGARFrameForSTM( ...
        prepared.sampledData, prepared.kSpaceLocations, prepared.DCF, ...
        prepared.spokeIndex, prepared.sensitivityMaps, d.imageSize, d.gridSize, ...
        nSpokesPerFrame, zSlice, calibrationSize, ...
        'CoordinateTransform', prepared.CA, 'TranslationVector', prepared.Cb, ...
        'VisibleObjectSize', d.visibleObjectSize, ...
        'ReturnDiagnostics', true, varargin{:});
    diagnostics.coordinateTransform = prepared.CA;
    diagnostics.translationVector = prepared.Cb;
end
