function params = setNormalizeGriddingParams(params, referenceVolumeA, frameParams)
%localNormalizeGriddingParams Set default griddingParams
%
% USAGE:
%    griddingParams = setNormalizeGriddingParams( ...
%        griddingParams, referenceVolumeA, frameParams);
% 
% DEFAULT OPTIONS:
% defaults = struct( ...
%     'gridOversamplingFactor', 1.375, ...
%     'kernelSize', [7 7 7], ...
%     'spatialSigma', 0, ...
%     'imageSize', defaultImageSize, ...
%     'PhaseWidth', 1, ...
%     'UseGpu', true, ...
%     'DisplaySlice', true, ...
%     'DisplaySliceIndex', [], ...
%     'ReturnDiagnostics', true, ...
%     'DensityScale', 1, ...
%     'OutputIsGpuArray', false, ...
%     'VisibleObjectSize', referenceSize);
% 
%  RJJ  |  09-25-2026


    if nargin<3, error('Must have 3 input arguments'); end
    if isempty(referenceVolumeA), error('referenceVolumeA is empty'); end
    if isempty(frameParams), error('frameParams is empty'); end

    if isempty(params), params = struct(); end
    if ~isstruct(params) || ~isscalar(params)
        error('griddingParams must be a scalar, struct, or empty.');
    end

    referenceSize = size(referenceVolumeA.A);
    if referenceSize(3) == 64
        defaultImageSize = [224 224 floor(referenceSize(3) * 1.5)];
    else
        defaultImageSize = [224 224 96];
    end

    defaults = struct( ...
        'gridOversamplingFactor', 1.375, ...
        'kernelSize', [7 7 7], ...
        'spatialSigma', 0, ...
        'imageSize', defaultImageSize, ...
        'PhaseWidth', 1, ...
        'UseGpu', true, ...
        'DisplaySlice', true, ...
        'DisplaySliceIndex', [], ...
        'ReturnDiagnostics', true, ...
        'DensityScale', 1, ...
        'OutputIsGpuArray', false, ...
        'VisibleObjectSize', referenceSize);
    fields = fieldnames(defaults);

    for iField = 1:numel(fields)
        name = fields{iField};
        if ~isfield(params, name) || isempty(params.(name))
            params.(name) = defaults.(name);
        end
    end

    validateattributes(params.gridOversamplingFactor, {'numeric'}, ...
        {'scalar', 'positive', 'finite'});
    validateattributes(params.kernelSize, {'numeric'}, ...
        {'vector', 'numel', 3, 'positive', 'integer'});
    validateattributes(params.spatialSigma, {'numeric'}, ...
        {'scalar', 'nonnegative', 'finite'});
    validateattributes(params.imageSize, {'numeric'}, ...
        {'vector', 'numel', 3, 'positive', 'integer'});
    validateattributes(params.PhaseWidth, {'numeric'}, ...
        {'scalar', 'nonzero', 'finite'});
    validateattributes(params.VisibleObjectSize, {'numeric'}, ...
        {'vector', 'numel', 3, 'positive', 'finite'});
    validateattributes(params.UseGpu, {'logical'}, {'scalar'});
    validateattributes(params.DisplaySlice, {'logical'}, {'scalar'});
    validateattributes(params.ReturnDiagnostics, {'logical'}, {'scalar'});
    validateattributes(params.OutputIsGpuArray, {'logical'}, {'scalar'});

    if isempty(params.DisplaySliceIndex)
        params.DisplaySliceIndex = floor(params.imageSize(3) / 2) + 1;
    end

    if params.DisplaySliceIndex < 1 || ...
            params.DisplaySliceIndex > params.imageSize(3)
        error('DisplaySliceIndex must be 1-based slice index within 1-%d.',...
            imageSize(3));
    end

    if any(frameParams.calibrationSize > params.imageSize(1:2))
        error('calibrationSize cannot exceed imageSize in-plane dimensions.');
    end

end

